# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-11 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_posts', '0003_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 11, 44, 44, 922138, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
