# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-15 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_posts', '0005_auto_20190728_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 8, 24, 56, 873705, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
