# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-15 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_posts', '0007_remove_post_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.TimeField(default=datetime.datetime(2019, 8, 15, 10, 57, 50, 780488, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
